#!/bin/bash
# Embedded Cross-Compile Agent - Auto-Fix Script
# Automatically fixes common pain points in cross-compilation projects

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[FIX]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[SKIP]${NC} $1"; }
log_fix() { echo -e "${BLUE}[FIX]${NC} $1"; }
log_done() { echo -e "${GREEN}[DONE]${NC} $1"; }

FIXES_APPLIED=0

# ============================================================
# Fix 1: CRLF Line Endings
# ============================================================
fix_crlf() {
    echo -e "\n${BLUE}=== 修复换行符 (CRLF → LF) ===${NC}"

    if ! command -v dos2unix &>/dev/null; then
        log_warn "dos2unix 未安装，跳过"
        return
    fi

    local count=0
    if [ -d "src" ]; then
        count=$(find src/ -maxdepth 8 -type f \( -name '*.c' -o -name '*.cpp' -o -name '*.h' \
            -o -name '*.sh' -o -name 'configure' -o -name 'Makefile*' \
            -o -name '*.pro' -o -name '*.pri' -o -name '*.conf' -o -name '*.json' \) \
            -exec file {} + 2>/dev/null | grep -c "CRLF" || true)
    fi

    if [ "$count" -gt 0 ]; then
        log_fix "修复 $count 个文件的换行符..."
        find src/ -maxdepth 8 -type f \( -name '*.c' -o -name '*.cpp' -o -name '*.h' \
            -o -name '*.sh' -o -name 'configure' -o -name 'Makefile*' \
            -o -name '*.pro' -o -name '*.pri' -o -name '*.conf' -o -name '*.json' \) \
            -exec dos2unix {} + 2>/dev/null
        log_done "换行符修复完成"
        FIXES_APPLIED=$((FIXES_APPLIED + 1))
    else
        log_info "无换行符问题"
    fi
}

# ============================================================
# Fix 2: Recursive Directory Cleanup
# ============================================================
fix_recursive_dirs() {
    echo -e "\n${BLUE}=== 修复递归嵌套目录 ===${NC}"

    local count=$(find . -maxdepth 10 -type d -name "alsa" -path "*/alsa/alsa*" 2>/dev/null | wc -l || true)

    if [ "$count" -gt 0 ]; then
        log_fix "发现 $count 个递归嵌套的 alsa 目录，正在清理..."
        find . -maxdepth 10 -path "*/alsa/alsa" -type d -exec rm -rf {} + 2>/dev/null || true
        log_done "递归目录清理完成"
        FIXES_APPLIED=$((FIXES_APPLIED + 1))
    else
        log_info "无递归目录问题"
    fi
}

# ============================================================
# Fix 3: Long Path Shortening
# ============================================================
fix_long_paths() {
    echo -e "\n${BLUE}=== 缩短过长路径 ===${NC}"

    local max_len=0
    local longest=""
    while IFS= read -r -d '' file; do
        len=${#file}
        if [ "$len" -gt "$max_len" ]; then
            max_len=$len
            longest=$file
        fi
    done < <(find . -maxdepth 15 -print0 2>/dev/null)

    if [ "$max_len" -gt 200 ]; then
        log_warn "最长路径 $max_len 字符: $longest"
        log_warn "建议手动缩短目录名，例如:"
        echo "       mv '交叉编译已经好的工具-我用的arm-buildroot-linux-gnueabi' compiled"
        echo "       mv '交叉编译用到的工具' src"
    else
        log_info "路径长度正常 ($max_len 字符)"
    fi
}

# ============================================================
# Fix 4: pkg-config Hardcoded Paths
# ============================================================
fix_pkgconfig() {
    echo -e "\n${BLUE}=== 修复 pkg-config 硬编码路径 ===${NC}"

    if [ ! -d "compiled" ]; then
        log_warn "未找到 compiled/ 目录，跳过"
        return
    fi

    local fixed=0
    find compiled/ -name "*.pc" -type f 2>/dev/null | while read pc_file; do
        # Check for hardcoded paths from other machines
        if grep -q "prefix=/home/book\|prefix=/home/[^h]" "$pc_file" 2>/dev/null; then
            log_fix "修复 $pc_file 中的硬编码路径"
            # Get the actual prefix (parent of the lib/pkgconfig directory)
            actual_prefix=$(dirname "$(dirname "$(realpath "$pc_file")")")
            sed -i "s|^prefix=.*|prefix=$actual_prefix|" "$pc_file"
            fixed=$((fixed + 1))
        fi
    done

    if [ "$fixed" -gt 0 ]; then
        log_done "修复了 $fixed 个 .pc 文件"
        FIXES_APPLIED=$((FIXES_APPLIED + 1))
    else
        log_info "无 pkg-config 路径问题"
    fi
}

# ============================================================
# Fix 5: Environment Variables Setup
# ============================================================
fix_env_vars() {
    echo -e "\n${BLUE}=== 配置环境变量 ===${NC}"

    # Detect toolchain prefix
    local prefix=""
    for p in arm-linux-gnueabi arm-linux-gnueabihf aarch64-linux-gnu riscv64-linux-gnu; do
        if command -v "${p}-gcc" &>/dev/null; then
            prefix="$p"
            break
        fi
    done

    if [ -z "$prefix" ]; then
        log_warn "未检测到交叉编译工具链，跳过环境变量配置"
        return
    fi

    # Create env setup script
    cat > env_setup.sh << EOF
#!/bin/bash
# Auto-generated by fix.sh - Source this file before cross-compiling
# Usage: source env_setup.sh

export CC=${prefix}-gcc
export CXX=${prefix}-g++
export AR=${prefix}-ar
export STRIP=${prefix}-strip
export RANLIB=${prefix}-ranlib
export OBJCOPY=${prefix}-objcopy
export OBJDUMP=${prefix}-objdump

# Set PKG_CONFIG_PATH if compiled libs exist
if [ -d "compiled" ]; then
    for pc_dir in compiled/*/build/lib/pkgconfig compiled/*/lib/pkgconfig; do
        if [ -d "\$pc_dir" ]; then
            export PKG_CONFIG_PATH="\$(realpath "\$pc_dir"):\${PKG_CONFIG_PATH:-}"
        fi
    done
fi

echo "Cross-compilation environment configured for: $prefix"
echo "  CC=\$CC"
echo "  CXX=\$CXX"
echo "  PKG_CONFIG_PATH=\$PKG_CONFIG_PATH"
EOF

    chmod +x env_setup.sh
    log_done "环境变量配置脚本已生成: env_setup.sh"
    log_info "使用方法: source env_setup.sh"
    FIXES_APPLIED=$((FIXES_APPLIED + 1))
}

# ============================================================
# Fix 6: Symlink Repair
# ============================================================
fix_symlinks() {
    echo -e "\n${BLUE}=== 修复符号链接 ===${NC}"

    # Find broken symlinks
    local broken=$(find . -maxdepth 5 -type l ! -exec test -e {} \; -print 2>/dev/null | head -20)

    if [ -n "$broken" ]; then
        log_warn "发现损坏的符号链接:"
        echo "$broken" | while read link; do
            echo "       $link -> $(readlink "$link" 2>/dev/null)"
        done
        log_warn "建议手动检查这些符号链接是否需要修复"
    else
        log_info "无损坏的符号链接"
    fi
}

# ============================================================
# Fix 7: Missing Dependencies Check
# ============================================================
fix_dependencies() {
    echo -e "\n${BLUE}=== 检查编译依赖 ===${NC}"

    local packages=(
        "gcc-arm-linux-gnueabi"
        "g++-arm-linux-gnueabi"
        "build-essential"
        "pkg-config"
        "dos2unix"
        "unzip"
        "rsync"
    )

    local missing=()
    for pkg in "${packages[@]}"; do
        if ! dpkg -l "$pkg" &>/dev/null; then
            missing+=("$pkg")
        fi
    done

    if [ ${#missing[@]} -gt 0 ]; then
        log_fix "缺少 ${#missing[@]} 个依赖包"
        echo "       运行以下命令安装:"
        echo "       sudo apt install ${missing[*]}"
    else
        log_info "所有依赖包已安装"
    fi
}

# ============================================================
# Main
# ============================================================
echo -e "${BLUE}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  Embedded Cross-Compile Agent - Auto Fix        ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════╝${NC}"

fix_crlf
fix_recursive_dirs
fix_long_paths
fix_pkgconfig
fix_env_vars
fix_symlinks
fix_dependencies

echo -e "\n${BLUE}=== 修复完成 ===${NC}"
if [ "$FIXES_APPLIED" -gt 0 ]; then
    echo -e "  ${GREEN}应用了 $FIXES_APPLIED 项修复${NC}"
else
    echo -e "  ${GREEN}未发现问题${NC}"
fi
echo ""
